In [1]:
# This script contains exercises on 
# manipulating arrays with numpy
import numpy as np
x = np.arange(0, 3**3)

#### 1. What is the length of x?

In [2]:
# Your code here
len(x)

27

#### 2. How do you get the first value out of x?

In [16]:
first = x[0]
print(first)
print(x)

0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
# Your code here
first = x[0]
print(first)

0


#### 3. How do you get the last value out of x?

In [17]:
# Your code here
last = x[-1]
print(last)

26


#### 4. How do you get the first 5 values out of x?

In [18]:
# Your code here
first_five = x[:5]
print(first_five)

[0 1 2 3 4]


#### 5. What about the last 5 values of x?

In [20]:
# Your code here
last_five = x[-5:]
print(last_five)

[22 23 24 25 26]


#### 6. How do you get every other value out of x?

In [21]:
# Your code here
every_other = x[::2]
print(every_other)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]



#### 7. Get the first 9 values of x, and reshape them to a 3x3 matrix. Assign this matrix to the variable `y`

In [25]:
 # Your code here
first_nine = x[:9]
print(first_nine)
y = first_nine.reshape(3,3)
print(y)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. How do you get the middle value out of y?

In [27]:
y = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
# Your code here
middle = np.median(y)
print(middle)

4.0


#### 9. How do you get the first row out of y?

In [29]:
# Your code here
top_row = y[0]
print(top_row)

[0 1 2]


#### 10. How do you get the first column out of y?

In [32]:
# Your code here
first_col = y[:,0]
print(first_col)

[0 3 6]


#### 11. Reshape x into a 3x3x3 cube. Assign this to the variable `z`

In [36]:
x = np.arange(0, 3**3)
# Your code here
print(x)
z = x.reshape(3,3,3) 
print(z)
z.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


(3, 3, 3)

#### 12. How do you get the "center" value from z?

In [41]:
z = np.array([
    [[ 0, 1, 2],
     [ 3, 4, 5],
     [ 6, 7, 8]],
    [[ 9,10,11],
     [12,13,14],
     [15,16,17]],
    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
# Your code here
mid_z = np.median(z)
print(mid_z)


13.0



#### 13. How do you take the total sum of z?

In [42]:
# Your code here
sum_z = np.sum(z)
print(sum_z)

351



#### 14. How do you take the sum along the first dimension of z?

In [ ]:
# Your code here
sum_z_firdim = np.sum(z,axis = 0)
print(sum_z_firdim)

[[27 30 33]
 [36 39 42]
 [45 48 51]]


#### 15. How do you take the sum along the last dimension of z?

In [47]:
# Your code here
# Your code here
sum_z_lastdim = np.sum(z,axis = -1)
print(sum_z_lastdim)

[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
